function generateToolMarkdown(tool: any): string {
  return "\n" +
    "# Tool: " + tool.name + "\n" +
    "\n" +
    "**ID:** \"" + tool.id + "\"  \n" +
    "**Runner:** \"" + tool.runner + "\"  \n" +
    "**Permissions:** " + (tool.permissions?.map((p: any) => "`" + p + "`").join(", ") || "None") + "\n" +
    "\n" +
    "## Description\n" +
    "\n" +
    (tool.description || "No description provided.") + "\n" +
    "\n" +
    "## Usage\n" +
    "\n" +
    "### Input Schema\n" +
    "\n" +
    "[TBD - Schema documentation will be added here]" + "\n" +
    "\n" +
    "### Output Schema\n" +
    "\n" +
    "[TBD - Schema documentation will be added here]" + "\n" +
    "\n" +
    "### Example\n" +
    "\n" +
    "[TBD - Usage example will be added here]" + "\n" +
    "\n" +
    "## Permissions\n" +
    "\n" +
    "This tool requires the following permissions:\n" +
    "\n" +
    (tool.permissions?.map((p: any) => `- \`${p}\``).join("\n") || "No special permissions required.") + "\n" +
    "\n" +
    "## Security Notes\n" +
    "\n" +
    "- Always validate input against the schema before execution\n" +
    "- Ensure caller has appropriate permissions before invoking this tool\n" +
    "- Monitor tool execution through EventBus telemetry\n" +
    "\n" +
    "\n" +
    "---\n" +
    "\n" +
    "*Generated by Arium CLI - Tools Documentation Generator*\n" +
    "";
}